In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import balanced_accuracy_score, accuracy_score, precision_score, recall_score, f1_score
import warnings

warnings.filterwarnings('ignore')

In [2]:
train_data=pd.read_csv('train_data.csv')
test_data=pd.read_csv('test_data.csv')

In [3]:
train_data.head()

,age,sex,on_thyroxine,query_on_thyroxine,on_antithyroid_meds,sick,pregnant,thyroid_surgery,I131_treatment,query_hypothyroid,...,goitre,tumor,hypopituitary,psych,TSH,T3,TT4,T4U,FTI,target
0,70.0,1.0,1,0,0,0,0,0,0,0,...,0,0,0,0,3.0,1.8,95.0,1.00,95.0,0
1,78.0,1.0,0,0,0,0,0,0,0,0,...,0,0,0,0,2.9,1.7,104.0,0.76,137.0,0
2,50.0,1.0,0,0,0,0,0,1,0,0,...,0,0,0,0,3.0,0.0,106.0,1.07,99.0,0
3,44.0,1.0,0,0,0,0,0,0,0,0,...,0,0,0,0,1.2,1.7,92.0,0.98,94.0,0
4,64.0,1.0,1,0,0,0,0,0,0,0,...,0,0,0,0,2.2,0.0,111.0,0.97,114.0,0

In [4]:
test_data.head()

,age,sex,on_thyroxine,query_on_thyroxine,on_antithyroid_meds,sick,pregnant,thyroid_surgery,I131_treatment,query_hypothyroid,...,goitre,tumor,hypopituitary,psych,TSH,T3,TT4,T4U,FTI,target
0,60.0,1.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.48,1.7,88.0,0.83,105.0,0
1,53.0,1.0,0,0,1,0,0,0,0,0,...,0,0,0,0,0.00,0.0,78.0,0.85,91.0,0
2,77.0,0.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.10,1.9,100.0,0.98,102.0,0
3,69.0,1.0,0,0,0,0,0,0,0,0,...,0,0,0,0,3.10,0.0,110.0,1.02,108.0,0
4,89.0,1.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.70,1.5,120.0,0.92,130.0,0

In [5]:
train_data.shape

(5356, 22)

In [6]:
test_data.shape

(1786, 22)

In [7]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5356 entries, 0 to 5355
Data columns (total 22 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   age                  5356 non-null   float64
 1   sex                  5356 non-null   float64
 2   on_thyroxine         5356 non-null   int64
 3   query_on_thyroxine   5356 non-null   int64
 4   on_antithyroid_meds  5356 non-null   int64
 5   sick                 5356 non-null   int64
 6   pregnant             5356 non-null   int64
 7   thyroid_surgery      5356 non-null   int64
 8   I131_treatment       5356 non-null   int64
 9   query_hypothyroid    5356 non-null   int64
 10  query_hyperthyroid   5356 non-null   int64
 11  lithium              5356 non-null   int64
 12  goitre               5356 non-null   int64
 13  tumor                5356 non-null   int64
 14  hypopituitary        5356 non-null   int64
 15  psych                5356 non-null   int64
 16  TSH                  5356 non-null   float64
 17  T3                   5356 non-null   float64
 18  TT4                  5356 non-null   float64
 19  T4U                  5356 non-null   float64
 20  FTI                  5356 non-null   float64
 21  target               5356 non-null   int64
dtypes: float64(7), int64(15)
memory usage: 920.7 KB

In [8]:
train_data.columns

Index(['age', 'sex', 'on_thyroxine', 'query_on_thyroxine',
       'on_antithyroid_meds', 'sick', 'pregnant', 'thyroid_surgery',
       'I131_treatment', 'query_hypothyroid', 'query_hyperthyroid', 'lithium',
       'goitre', 'tumor', 'hypopituitary', 'psych', 'TSH', 'T3', 'TT4', 'T4U',
       'FTI', 'target'],
      dtype='object')

In [9]:
train_data.describe().T

,count,mean,std,min,25%,50%,75%,max
age,5356.0,52.221621,18.489727,1.0,38.00,55.00,67.00,97.00
sex,5356.0,0.640777,0.479818,0.0,0.00,1.00,1.00,1.00
on_thyroxine,5356.0,0.111837,0.315195,0.0,0.00,0.00,0.00,1.00
query_on_thyroxine,5356.0,0.018857,0.136034,0.0,0.00,0.00,0.00,1.00
on_antithyroid_meds,5356.0,0.013256,0.114380,0.0,0.00,0.00,0.00,1.00
sick,5356.0,0.035661,0.185461,0.0,0.00,0.00,0.00,1.00
pregnant,5356.0,0.002801,0.052851,0.0,0.00,0.00,0.00,1.00
thyroid_surgery,5356.0,0.014376,0.119048,0.0,0.00,0.00,0.00,1.00
I131_treatment,5356.0,0.019417,0.138000,0.0,0.00,0.00,0.00,1.00
query_hypothyroid,5356.0,0.066654,0.249445,0.0,0.00,0.00,0.00,1.00
query_hyperthyroid,5356.0,0.068148,0.252023,0.0,0.00,0.00,0.00,1.00
lithium,5356.0,0.012323,0.110332,0.0,0.00,0.00,0.00,1.00
goitre,5356.0,0.009335,0.096176,0.0,0.00,0.00,0.00,1.00
tumor,5356.0,0.022218,0.147406,0.0,0.00,0.00,0.00,1.00
hypopituitary,5356.0,0.000000,0.000000,0.0,0.00,0.00,0.00,0.00
psych,5356.0,0.053771,0.225587,0.0,0.00,0.00,0.00,1.00
TSH,5356.0,5.108164,25.682564,0.0,0.36,1.30,2.50,530.00
T3,5356.0,1.465338,1.120083,0.0,0.00,1.70,2.20,18.00
TT4,5356.0,104.657797,32.119558,0.0,87.00,103.00,121.00,430.00
T4U,5356.0,0.927538,0.247707,0.0,0.85,0.96,1.05,1.96
FTI,5356.0,105.854040,40.444633,0.0,91.00,107.00,124.00,642.00
target,5356.0,0.130508,0.403017,0.0,0.00,0.00,0.00,2.00

In [10]:
train_data.isnull().sum()

age                    0
sex                    0
on_thyroxine           0
query_on_thyroxine     0
on_antithyroid_meds    0
sick                   0
pregnant               0
thyroid_surgery        0
I131_treatment         0
query_hypothyroid      0
query_hyperthyroid     0
lithium                0
goitre                 0
tumor                  0
hypopituitary          0
psych                  0
TSH                    0
T3                     0
TT4                    0
T4U                    0
FTI                    0
target                 0
dtype: int64

In [11]:
train_data.target.value_counts()

target
0    4788
1     437
2     131
Name: count, dtype: int64

Training data

In [12]:
X_train = train_data.drop(['target'], axis=1).copy()
y_train = train_data['target'].copy()

In [13]:
X_train.head()

,age,sex,on_thyroxine,query_on_thyroxine,on_antithyroid_meds,sick,pregnant,thyroid_surgery,I131_treatment,query_hypothyroid,...,lithium,goitre,tumor,hypopituitary,psych,TSH,T3,TT4,T4U,FTI
0,70.0,1.0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,3.0,1.8,95.0,1.00,95.0
1,78.0,1.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,2.9,1.7,104.0,0.76,137.0
2,50.0,1.0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,3.0,0.0,106.0,1.07,99.0
3,44.0,1.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1.2,1.7,92.0,0.98,94.0
4,64.0,1.0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,2.2,0.0,111.0,0.97,114.0

In [14]:
X_train.shape,y_train.shape

((5356, 21), (5356,))

In [15]:
X_test = test_data.drop(['target'], axis=1).copy()
y_test = test_data['target'].copy()

In [16]:
X_test.shape,y_test.shape

((1786, 21), (1786,))

Model Training

In [17]:
clf = RandomForestClassifier()
clf.fit(X_train, y_train)

RandomForestClassifier()

On Train data

In [18]:
y_pred = clf.predict(X_train)

print('\n------------------ Confusion Matrix -----------------\n')
print(confusion_matrix(y_train, y_pred))

print('\n-------------------- Key Metrics --------------------')
print('\nAccuracy: {:.2f}'.format(accuracy_score(y_train, y_pred)))
print('Balanced Accuracy: {:.2f}\n'.format(balanced_accuracy_score(y_train, y_pred)))

print('Micro Precision: {:.2f}'.format(precision_score(y_train, y_pred, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_train, y_pred, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_train, y_pred, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_train, y_pred, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_train, y_pred, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_train, y_pred, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_train, y_pred, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_train, y_pred, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_train, y_pred, average='weighted')))

print('\n--------------- Classification Report ---------------\n')
print(classification_report(y_train, y_pred))

------------------ Confusion Matrix -----------------

[[4788    0    0]
 [   0  437    0]
 [   0    0  131]]

-------------------- Key Metrics --------------------

Accuracy: 1.00
Balanced Accuracy: 1.00

Micro Precision: 1.00
Micro Recall: 1.00
Micro F1-score: 1.00

Macro Precision: 1.00
Macro Recall: 1.00
Macro F1-score: 1.00

Weighted Precision: 1.00
Weighted Recall: 1.00
Weighted F1-score: 1.00

--------------- Classification Report ---------------

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      4788
           1       1.00      1.00      1.00       437
           2       1.00      1.00      1.00       131

    accuracy                           1.00      5356
   macro avg       1.00      1.00      1.00      5356
weighted avg       1.00      1.00      1.00      5356

On test Data

In [19]:
y_pred = clf.predict(X_test)

print('\n------------------ Confusion Matrix -----------------\n')
print(confusion_matrix(y_test, y_pred))

print('\n-------------------- Key Metrics --------------------')
print('\nAccuracy: {:.2f}'.format(accuracy_score(y_test, y_pred)))
print('Balanced Accuracy: {:.2f}\n'.format(balanced_accuracy_score(y_test, y_pred)))

print('Micro Precision: {:.2f}'.format(precision_score(y_test, y_pred, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_test, y_pred, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_test, y_pred, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_test, y_pred, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_test, y_pred, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_test, y_pred, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_test, y_pred, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_test, y_pred, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_test, y_pred, average='weighted')))

print('\n--------------- Classification Report ---------------\n')
print(classification_report(y_test, y_pred))

------------------ Confusion Matrix -----------------

[[1587    6    4]
 [   0  145    0]
 [  11    0   33]]

-------------------- Key Metrics --------------------

Accuracy: 0.99
Balanced Accuracy: 0.91

Micro Precision: 0.99
Micro Recall: 0.99
Micro F1-score: 0.99

Macro Precision: 0.95
Macro Recall: 0.91
Macro F1-score: 0.93

Weighted Precision: 0.99
Weighted Recall: 0.99
Weighted F1-score: 0.99

--------------- Classification Report ---------------

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      1597
           1       0.96      1.00      0.98       145
           2       0.89      0.75      0.81        44

    accuracy                           0.99      1786
   macro avg       0.95      0.91      0.93      1786
weighted avg       0.99      0.99      0.99      1786

Predective system

In [20]:
test_query=X_test.iloc[201].values.reshape(1,-1)

In [21]:
test_query

array([[3.60e+01, 0.00e+00, 0.00e+00, 0.00e+00, 0.00e+00, 0.00e+00,
        0.00e+00, 0.00e+00, 0.00e+00, 0.00e+00, 1.00e+00, 0.00e+00,
        0.00e+00, 0.00e+00, 0.00e+00, 0.00e+00, 3.00e-02, 4.00e+00,
        1.78e+02, 1.14e+00, 1.56e+02]])

In [22]:
result=clf.predict(test_query)
print(result)

if result==0:
    print('negative')
elif result==1:
    print('hypothyroid')
else:
    print('hyperthyroid')

[2]
hyperthyroid

In [23]:
value = 2
result1 = test_data[test_data['target'] == value]
print(result1)

       age  sex  on_thyroxine  query_on_thyroxine  on_antithyroid_meds  sick  \
22    36.0  1.0             0                   0                    0     0
41    59.0  1.0             0                   0                    0     0
125   56.0  1.0             0                   0                    0     0
195   42.0  0.0             0                   0                    0     0
201   36.0  0.0             0                   0                    0     0
258   22.0  1.0             0                   0                    0     0
266   28.0  1.0             0                   0                    0     0
272   57.0  0.0             0                   0                    0     0
418   72.0  1.0             0                   0                    0     0
434   37.0  0.0             0                   0                    0     0
452   59.0  1.0             0                   0                    0     0
464   39.0  0.0             1                   0                    0     0
612   66.0  1.0             0                   0                    0     0
627   77.0  1.0             0                   0                    0     0
648   33.0  0.0             0                   0                    0     0
663   58.0  1.0             0                   0                    1     0
685   38.0  0.0             0                   0                    0     0
693   42.0  1.0             0                   0                    1     0
789   84.0  0.0             0                   0                    0     0
799   54.0  1.0             0                   0                    0     0
815   25.0  1.0             0                   0                    0     0
839   53.0  1.0             0                   0                    0     0
910   55.0  1.0             0                   0                    0     0
915   34.0  1.0             0                   0                    0     0
984   49.0  1.0             0                   0                    0     0
1013  79.0  0.0             0                   0                    0     0
1034  65.0  1.0             0                   0                    0     0
1074  35.0  0.0             0                   0                    0     0
1099  76.0  0.0             0                   0                    0     0
1147  31.0  1.0             0                   0                    0     0
1163  72.0  1.0             0                   0                    0     0
1190  15.0  1.0             0                   0                    0     0
1246  65.0  1.0             0                   0                    0     0
1263  55.0  1.0             0                   0                    0     0
1265  33.0  1.0             0                   0                    0     0
1273  33.0  1.0             0                   0                    0     0
1286  49.0  1.0             0                   0                    0     0
1303  31.0  1.0             0                   0                    0     0
1493  59.0  0.0             0                   0                    0     0
1535  48.0  1.0             0                   0                    0     0
1561  39.0  1.0             0                   0                    0     0
1627  73.0  1.0             0                   0                    0     0
1755  61.0  1.0             0                   0                    0     0
1769  41.0  1.0             0                   0                    0     0

      pregnant  thyroid_surgery  I131_treatment  query_hypothyroid  ...  \
22           0                0               0                  0  ...
41           0                0               0                  0  ...
125          0                0               0                  0  ...
195          0                0               0                  0  ...
201          0                0               0                  0  ...
258          0                0               0                  0  ...
266          0                0               0                  0  ...
272          0                0               0                  0  ...
418          0                0               0                  0  ...
434          0                0               0                  0  ...
452          0                0               0                  0  ...
464          0                0               0                  0  ...
612          0                0               0                  0  ...
627          0                0               0                  0  ...
648          0                0               0                  0  ...
663          0                0               0                  0  ...
685          0                0               0                  0  ...
693          0                0               0                  0  ...
789          0                0               0                  0  ...
799          0                0               1                  0  ...
815          0                0               0                  0  ...
839          0                0               0                  0  ...
910          0                0               0                  0  ...
915          0                0               0                  0  ...
984          0                0               0                  0  ...
1013         0                0               0                  0  ...
1034         0                0               0                  0  ...
1074         0                0               0                  0  ...
1099         0                0               0                  0  ...
1147         0                0               0                  0  ...
1163         0                0               0                  0  ...
1190         0                0               0                  0  ...
1246         0                0               0                  0  ...
1263         0                0               0                  0  ...
1265         0                0               0                  0  ...
1273         0                0               0                  0  ...
1286         0                0               0                  0  ...
1303         0                0               0                  0  ...
1493         0                0               0                  0  ...
1535         0                0               0                  0  ...
1561         0                0               0                  0  ...
1627         0                0               0                  0  ...
1755         0                0               0                  0  ...
1769         0                0               0                  0  ...

      goitre  tumor  hypopituitary  psych        TSH         T3    TT4   T4U  \
22         0      0              0      0   0.085000   4.500000  198.0  1.15
41         0      1              0      0   0.050000   3.600000   94.0  1.02
125        0      0              0      0   0.250000   3.200000  268.0  1.01
195        0      0              0      0   0.045000   3.100000  119.0  0.80
201        0      0              0      0   0.030000   4.000000  178.0  1.14
258        0      0              0      0   0.055000   6.200000  386.0  1.02
266        0      0              0      0   0.100000   3.000000  235.0  1.38
272        0      0              0      0   0.050000   3.700000  244.0  0.95
418        0      0              0      0   0.000000   0.000000  161.0  0.90
434        0      0              0      0   0.000000   4.300000  187.0  0.96
452        0      0              0      0   0.000000   0.000000  160.0  0.85
464        0      0              0      0   0.105000   4.100000  131.0  0.95
612        0      0              0      0   0.040000   4.900000  249.0  0.86
627        0      0              0      0   0.030000  13.299999  410.0  0.79
648        0      0              0      0   0.015000   5.000000  244.0  0.67
663        0      0              0      0   0.150000   3.000000  148.0  0.91
685        0      0              0      0   9.599999   4.800000  168.0  0.28
693        0      0              0      0   0.025000   3.100000  136.0  1.00
789        0      0              0      0  14.000000   6.700000  280.0  0.85
799        0      0              0      0   0.075000   5.000000  216.0  0.86
815        0      1              0      0   1.000000   3.200000  117.0  1.11
839        0      0              0      0   0.020000   4.300000  250.0  1.01
910        0      0              0      0   0.200000   3.600000  301.0  1.75
915        0      0              0      0   0.000000   5.300000  181.0  1.04
984        0      0              0      0   0.050000   0.000000  193.0  1.05
1013       0      0              0      0   0.030000   4.100000  160.0  0.78
1034       0      0              0      0   0.020000   3.100000  114.0  0.91
1074       0      0              0      0   0.250000   4.600000  275.0  1.06
1099       0      0              0      0   0.065000   3.900000  186.0  0.94
1147       0      0              0      0   0.000000   0.000000  196.0  0.94
1163       0      0              0      0   0.015000   2.900000  198.0  0.91
1190       0      0              0      0   0.015000   6.000000  250.0  0.80
1246       0      0              0      0   0.020000   0.000000  161.0  1.02
1263       0      0              0      0   0.000000   5.500000  214.0  0.91
1265       0      0              0      0   0.055000   0.000000  148.0  0.95
1273       0      0              0      0   0.025000   5.300000  278.0  0.78
1286       0      0              0      0   0.025000   3.700000  178.0  0.00
1303       0      0              0      0   0.000000   3.000000  169.0  0.96
1493       0      0              0      0  24.000000   8.900000  218.0  0.83
1535       0      0              0      0   0.300000   8.900000  212.0  0.88
1561       0      0              0      0   0.020000   4.000000  209.0  1.06
1627       0      1              0      0   0.025000   4.400000  235.0  0.92
1755       0      0              0      0   0.025000   8.000000  202.0  0.00
1769       0      0              0      0   0.150000   7.300000  430.0  1.09

        FTI  target
22    172.0       2
41     92.0       2
125   266.0       2
195   149.0       2
201   156.0       2
258   378.0       2
266   171.0       2
272   256.0       2
418   180.0       2
434   194.0       2
452   188.0       2
464   138.0       2
612   290.0       2
627   519.0       2
648   362.0       2
663   163.0       2
685   612.0       2
693   136.0       2
789   329.0       2
799   251.0       2
815   105.0       2
839   247.0       2
910   172.0       2
915   174.0       2
984   184.0       2
1013  204.0       2
1034  126.0       2
1074  259.0       2
1099  198.0       2
1147  209.0       2
1163  217.0       2
1190  312.0       2
1246  158.0       2
1263  236.0       2
1265  156.0       2
1273  356.0       2
1286    0.0       2
1303  176.0       2
1493  264.0       2
1535  240.0       2
1561  197.0       2
1627  255.0       2
1755    0.0       2
1769  395.0       2

[44 rows x 22 columns]

Pickle Model

In [24]:
import pickle

with open('model.pkl','wb') as f:
    pickle.dump(clf,f)

In [25]:
with open('model.pkl','rb') as f:
    model=pickle.load(f)

In [26]:
diagnoses = {
    0: 'negative',
    1: 'hypothyroid',
    2: 'hyperthyroid'
}

output=model.predict(test_query)
prediction=diagnoses.get(output[0])
print(prediction)

hyperthyroid

In [27]:
import pandas as pd

existing_csv_file = "test_data.csv"
df = pd.read_csv(existing_csv_file)

# Manipulate DataFrame as needed
# For example, select specific rows based on conditions
new_df = df[df['target'] == 2]

# Write the new DataFrame to a new CSV file
new_csv_file = "hyper.csv"
new_df.to_csv(new_csv_file, index=False)  # Set index=False to avoid writing row indices

In [28]:
import pandas as pd

existing_csv_file = "test_data.csv"
df = pd.read_csv(existing_csv_file)

# Manipulate DataFrame as needed
# For example, select specific rows based on conditions
new_df = df[df['target'] == 1]

# Write the new DataFrame to a new CSV file
new_csv_file = "hyp0.csv"
new_df.to_csv(new_csv_file, index=False)  # Set index=False to avoid writing row indices

In [1]:
pip show scikit-learn

Name: scikit-learn
Version: 1.2.2
Summary: A set of python modules for machine learning and data mining
Home-page: http://scikit-learn.org
Author:
Author-email:
License: new BSD
Location: C:\ProgramData\anaconda3\Lib\site-packages
Requires: joblib, numpy, scipy, threadpoolctl
Required-by: imbalanced-learn
Note: you may need to restart the kernel to use updated packages.